services:
    backend:
        container_name: backend-shopper-taxi-api
        build: ./backend
        ports:
            - "8080:8080"
        working_dir: /backend-shopper-taxi-api
        volumes:
            - ./backend/src:/backend-shopper-taxi-api/src

        env_file:
            - .env.docker
        healthcheck:
            test: ["CMD", "lsof", "-t", "-i:8080"]
            timeout: 10s
            retries: 5
        depends_on:
            - postgres

    postgres:
        container_name: db-shopper-taxi-app
        image: bitnami/postgresql:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=shopper_taxi_app

    frontend:
        build:
            context: ./frontend
        container_name: frontend-shopper-taxi-api
        ports:
            - "80:80"
        depends_on:
            - backend
